#!/bin/bash

i=0
dirs=($@)
dir

while [[ $i -lt $# ]]; do
	dir="$ROOT/${dirs[$i]}"
	if [[ -e $dir ]]; then
		echo -e "=> \033[0;34mDirectory '$dir' was deleted .\033[0m"
		rm $dir
	fi
	((i=i+1))
done
