#!/bin/bash

link=${1:?'required argument (path)'}
target=${2:?'required argument (target)'}
rejected='\033[%dm[%s] "%s" - %s\033[0m\r\n'
resolved='\033[%dm[%s] "%s" -> "%s"\033[0m\r\n'

delay 260

if [[ ! -d "$target" ]]; then
	printf "$rejected" 31 "$(center 6 FAIL)" "$target" "unexisted target directory"
	exit 1
fi

if [[ -d "$ROOT/$link" ]]; then
	printf "$rejected" 33 "$(center 6 FAIL)" "$link" "directory was already existed"
	exit 1
fi 

printf "$resolved" 32 "$(center 6 LINK)" "$link" "$target"

ln -s "$target" "$ROOT/$link"
