#!/bin/bash

ROOT=${1:?'required parameter (root_dir)'}

echo "Your root directory is: $ROOT\n\n"

export SHELL="$(command -v bash)"
export HOME="$ROOT/home"
export TMPDIR="$ROOT/tmp"
export PREFIX="$ROOT/usr"
export SVDIR="$PREFIX/var/service"
export LOGDIR="$PRFIX/var/log"
export _="$PREFIX/bin/env"
