# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Starting - Ethereal OS
      run: source boot

    - name: File Structure
      run: du -h

    - name: Removing - Ethereal OS
      run: sbin/clean

    - name: Listing Files
      run: ls -RAl

